# Generated by Django 5.2.16 on 2026-08-03 14:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='idade',
            new_name='age',
        ),
    ]
